### ISSUE TITLE
Can't get toast to pop up longer.

### ISSUE THREAD

**Issue by lazyb5** [Anthonyrules144/Spotify-Toast#8]
I can't get the variable in the toast section to change from 65. Don't know if this is a bug or I'm doing something wrong. Thanks for making the program been looking forever for a functioning one with recent versions.

**Comment by ScarletLovell** [comment]
I'll check this in a bit. Sorry I didn't see this, I didn't get notified apparently.

**Comment by ScarletLovell** [comment]
In the next version, the toast mode will be revamped a little bit so it has more customization. Will release as soon as I can

**Comment by ScarletLovell** [comment]
v2.1 (The Toast Update) https://github.com/Ashleyz4/Spotify-Toast/commit/1dfbc766b12f1d5e9275e53810afe0303304b31f has been released https://github.com/Ashleyz4/Spotify-Toast/releases/tag/2.1
